### ISSUE TITLE
Hex -> ASCII for \n (0A) Not working

### ISSUE THREAD

**Issue by jigar599** [npp-plugins/converter#12]
When you convert Hex : \n(0A) to ASCII it gets removed.
The new line should remain as it is.

**Comment by user21760** [comment]
I agree that it would be useful. Something like a multiline option.
But I don't think it should be the default behaviour, it could cause unexpected results for other use cases, since there would be no difference between "41 \n 41" and "41 0A 41" after converting (where \n is the new line control). 
This would be an issue, for example, when using \n for some long chain of hex values just for presentation purposes (like this extension itself does), where the text potentially include 0A as part of its content.

**Comment by jigar599** [comment]
According to my thought it should not remove the data 0A when converting from Hex -> ASCII, its issue because it causes data removal by this application which is not correct.

**Comment by donho** [comment]
Tested with converter v4.5 & Notepad++ v8.6.2 (x64) - works fine to me.
It seems this issue has been fixed.
Otherwise please provide the instructions to reproduce it.
